version: 2.1
orbs:
  dockerize: sandbox/dockerize@dev:0.0.1

jobs:
  build:
    docker: 
      - image: circleci/node
      - image: circleci/postgres
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - dockerize/wait:
          service: tcp://127.0.0.1:5432